// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ai_engine.proto

package ai_engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message types for creative generation
type GenerateCreativeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CampaignId      string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	CreativeType    string                 `protobuf:"bytes,2,opt,name=creative_type,json=creativeType,proto3" json:"creative_type,omitempty"` // "image", "video", "text", "carousel"
	Parameters      map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Platforms       []string               `protobuf:"bytes,4,rep,name=platforms,proto3" json:"platforms,omitempty"`
	TargetAudience  *TargetAudience        `protobuf:"bytes,5,opt,name=target_audience,json=targetAudience,proto3" json:"target_audience,omitempty"`
	BrandGuidelines *BrandGuidelines       `protobuf:"bytes,6,opt,name=brand_guidelines,json=brandGuidelines,proto3" json:"brand_guidelines,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateCreativeRequest) Reset() {
	*x = GenerateCreativeRequest{}
	mi := &file_ai_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCreativeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCreativeRequest) ProtoMessage() {}

func (x *GenerateCreativeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCreativeRequest.ProtoReflect.Descriptor instead.
func (*GenerateCreativeRequest) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateCreativeRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *GenerateCreativeRequest) GetCreativeType() string {
	if x != nil {
		return x.CreativeType
	}
	return ""
}

func (x *GenerateCreativeRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *GenerateCreativeRequest) GetPlatforms() []string {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *GenerateCreativeRequest) GetTargetAudience() *TargetAudience {
	if x != nil {
		return x.TargetAudience
	}
	return nil
}

func (x *GenerateCreativeRequest) GetBrandGuidelines() *BrandGuidelines {
	if x != nil {
		return x.BrandGuidelines
	}
	return nil
}

type GenerateCreativeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Variations    []*CreativeVariation   `protobuf:"bytes,3,rep,name=variations,proto3" json:"variations,omitempty"`
	Metadata      *GenerationMetadata    `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCreativeResponse) Reset() {
	*x = GenerateCreativeResponse{}
	mi := &file_ai_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCreativeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCreativeResponse) ProtoMessage() {}

func (x *GenerateCreativeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCreativeResponse.ProtoReflect.Descriptor instead.
func (*GenerateCreativeResponse) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateCreativeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateCreativeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateCreativeResponse) GetVariations() []*CreativeVariation {
	if x != nil {
		return x.Variations
	}
	return nil
}

func (x *GenerateCreativeResponse) GetMetadata() *GenerationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Message types for campaign analysis
type AnalyzeCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Metrics       []string               `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	AnalysisType  string                 `protobuf:"bytes,3,opt,name=analysis_type,json=analysisType,proto3" json:"analysis_type,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeCampaignRequest) Reset() {
	*x = AnalyzeCampaignRequest{}
	mi := &file_ai_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeCampaignRequest) ProtoMessage() {}

func (x *AnalyzeCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeCampaignRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeCampaignRequest) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeCampaignRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *AnalyzeCampaignRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *AnalyzeCampaignRequest) GetAnalysisType() string {
	if x != nil {
		return x.AnalysisType
	}
	return ""
}

func (x *AnalyzeCampaignRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type AnalyzeCampaignResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Analysis        *AnalysisResult        `protobuf:"bytes,3,opt,name=analysis,proto3" json:"analysis,omitempty"`
	Recommendations []*Recommendation      `protobuf:"bytes,4,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeCampaignResponse) Reset() {
	*x = AnalyzeCampaignResponse{}
	mi := &file_ai_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeCampaignResponse) ProtoMessage() {}

func (x *AnalyzeCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeCampaignResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeCampaignResponse) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeCampaignResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnalyzeCampaignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AnalyzeCampaignResponse) GetAnalysis() *AnalysisResult {
	if x != nil {
		return x.Analysis
	}
	return nil
}

func (x *AnalyzeCampaignResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// Message types for agent workflows
type AgentWorkflowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkflowType   string                 `protobuf:"bytes,1,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	UserQuery      string                 `protobuf:"bytes,2,opt,name=user_query,json=userQuery,proto3" json:"user_query,omitempty"`
	Context        map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AvailableTools []string               `protobuf:"bytes,4,rep,name=available_tools,json=availableTools,proto3" json:"available_tools,omitempty"`
	CampaignId     string                 `protobuf:"bytes,5,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentWorkflowRequest) Reset() {
	*x = AgentWorkflowRequest{}
	mi := &file_ai_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentWorkflowRequest) ProtoMessage() {}

func (x *AgentWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentWorkflowRequest.ProtoReflect.Descriptor instead.
func (*AgentWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{4}
}

func (x *AgentWorkflowRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *AgentWorkflowRequest) GetUserQuery() string {
	if x != nil {
		return x.UserQuery
	}
	return ""
}

func (x *AgentWorkflowRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *AgentWorkflowRequest) GetAvailableTools() []string {
	if x != nil {
		return x.AvailableTools
	}
	return nil
}

func (x *AgentWorkflowRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type AgentWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	ToolsUsed     []*ToolUsage           `protobuf:"bytes,4,rep,name=tools_used,json=toolsUsed,proto3" json:"tools_used,omitempty"`
	Metadata      *WorkflowMetadata      `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentWorkflowResponse) Reset() {
	*x = AgentWorkflowResponse{}
	mi := &file_ai_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentWorkflowResponse) ProtoMessage() {}

func (x *AgentWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentWorkflowResponse.ProtoReflect.Descriptor instead.
func (*AgentWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{5}
}

func (x *AgentWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentWorkflowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentWorkflowResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AgentWorkflowResponse) GetToolsUsed() []*ToolUsage {
	if x != nil {
		return x.ToolsUsed
	}
	return nil
}

func (x *AgentWorkflowResponse) GetMetadata() *WorkflowMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Message types for insights
type InsightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	InsightType   string                 `protobuf:"bytes,2,opt,name=insight_type,json=insightType,proto3" json:"insight_type,omitempty"`
	TimeRange     string                 `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightsRequest) Reset() {
	*x = InsightsRequest{}
	mi := &file_ai_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightsRequest) ProtoMessage() {}

func (x *InsightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightsRequest.ProtoReflect.Descriptor instead.
func (*InsightsRequest) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{6}
}

func (x *InsightsRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *InsightsRequest) GetInsightType() string {
	if x != nil {
		return x.InsightType
	}
	return ""
}

func (x *InsightsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *InsightsRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type InsightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Insights      []*Insight             `protobuf:"bytes,3,rep,name=insights,proto3" json:"insights,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightsResponse) Reset() {
	*x = InsightsResponse{}
	mi := &file_ai_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightsResponse) ProtoMessage() {}

func (x *InsightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightsResponse.ProtoReflect.Descriptor instead.
func (*InsightsResponse) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{7}
}

func (x *InsightsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InsightsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InsightsResponse) GetInsights() []*Insight {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *InsightsResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// Shared data structures
type TargetAudience struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Demographics     map[string]string      `protobuf:"bytes,1,rep,name=demographics,proto3" json:"demographics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Interests        []string               `protobuf:"bytes,2,rep,name=interests,proto3" json:"interests,omitempty"`
	Behaviors        []string               `protobuf:"bytes,3,rep,name=behaviors,proto3" json:"behaviors,omitempty"`
	CustomAttributes map[string]string      `protobuf:"bytes,4,rep,name=custom_attributes,json=customAttributes,proto3" json:"custom_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TargetAudience) Reset() {
	*x = TargetAudience{}
	mi := &file_ai_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetAudience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetAudience) ProtoMessage() {}

func (x *TargetAudience) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetAudience.ProtoReflect.Descriptor instead.
func (*TargetAudience) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{8}
}

func (x *TargetAudience) GetDemographics() map[string]string {
	if x != nil {
		return x.Demographics
	}
	return nil
}

func (x *TargetAudience) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *TargetAudience) GetBehaviors() []string {
	if x != nil {
		return x.Behaviors
	}
	return nil
}

func (x *TargetAudience) GetCustomAttributes() map[string]string {
	if x != nil {
		return x.CustomAttributes
	}
	return nil
}

type BrandGuidelines struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Colors           []string               `protobuf:"bytes,1,rep,name=colors,proto3" json:"colors,omitempty"`
	Fonts            []string               `protobuf:"bytes,2,rep,name=fonts,proto3" json:"fonts,omitempty"`
	VoiceTone        string                 `protobuf:"bytes,3,opt,name=voice_tone,json=voiceTone,proto3" json:"voice_tone,omitempty"`
	StylePreferences map[string]string      `protobuf:"bytes,4,rep,name=style_preferences,json=stylePreferences,proto3" json:"style_preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BrandAssets      []string               `protobuf:"bytes,5,rep,name=brand_assets,json=brandAssets,proto3" json:"brand_assets,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BrandGuidelines) Reset() {
	*x = BrandGuidelines{}
	mi := &file_ai_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandGuidelines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandGuidelines) ProtoMessage() {}

func (x *BrandGuidelines) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandGuidelines.ProtoReflect.Descriptor instead.
func (*BrandGuidelines) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{9}
}

func (x *BrandGuidelines) GetColors() []string {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *BrandGuidelines) GetFonts() []string {
	if x != nil {
		return x.Fonts
	}
	return nil
}

func (x *BrandGuidelines) GetVoiceTone() string {
	if x != nil {
		return x.VoiceTone
	}
	return ""
}

func (x *BrandGuidelines) GetStylePreferences() map[string]string {
	if x != nil {
		return x.StylePreferences
	}
	return nil
}

func (x *BrandGuidelines) GetBrandAssets() []string {
	if x != nil {
		return x.BrandAssets
	}
	return nil
}

type CreativeVariation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	VariationId          string                 `protobuf:"bytes,1,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
	ContentUrl           string                 `protobuf:"bytes,2,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	ContentType          string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	GenerationParameters map[string]string      `protobuf:"bytes,4,rep,name=generation_parameters,json=generationParameters,proto3" json:"generation_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PerformanceScore     float32                `protobuf:"fixed32,5,opt,name=performance_score,json=performanceScore,proto3" json:"performance_score,omitempty"`
	IsApproved           bool                   `protobuf:"varint,6,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreativeVariation) Reset() {
	*x = CreativeVariation{}
	mi := &file_ai_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreativeVariation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreativeVariation) ProtoMessage() {}

func (x *CreativeVariation) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreativeVariation.ProtoReflect.Descriptor instead.
func (*CreativeVariation) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{10}
}

func (x *CreativeVariation) GetVariationId() string {
	if x != nil {
		return x.VariationId
	}
	return ""
}

func (x *CreativeVariation) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *CreativeVariation) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreativeVariation) GetGenerationParameters() map[string]string {
	if x != nil {
		return x.GenerationParameters
	}
	return nil
}

func (x *CreativeVariation) GetPerformanceScore() float32 {
	if x != nil {
		return x.PerformanceScore
	}
	return 0
}

func (x *CreativeVariation) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *CreativeVariation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GenerationMetadata struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ModelUsed             string                 `protobuf:"bytes,1,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	Parameters            map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GenerationTimeSeconds float32                `protobuf:"fixed32,3,opt,name=generation_time_seconds,json=generationTimeSeconds,proto3" json:"generation_time_seconds,omitempty"`
	Timestamp             string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GenerationMetadata) Reset() {
	*x = GenerationMetadata{}
	mi := &file_ai_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationMetadata) ProtoMessage() {}

func (x *GenerationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationMetadata.ProtoReflect.Descriptor instead.
func (*GenerationMetadata) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{11}
}

func (x *GenerationMetadata) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *GenerationMetadata) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *GenerationMetadata) GetGenerationTimeSeconds() float32 {
	if x != nil {
		return x.GenerationTimeSeconds
	}
	return 0
}

func (x *GenerationMetadata) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type AnalysisResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId      string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	Metrics         map[string]float32     `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	Summary         string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Insights        []string               `protobuf:"bytes,4,rep,name=insights,proto3" json:"insights,omitempty"`
	ConfidenceScore string                 `protobuf:"bytes,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_ai_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{12}
}

func (x *AnalysisResult) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *AnalysisResult) GetMetrics() map[string]float32 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *AnalysisResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalysisResult) GetInsights() []string {
	if x != nil {
		return x.Insights
	}
	return nil
}

func (x *AnalysisResult) GetConfidenceScore() string {
	if x != nil {
		return x.ConfidenceScore
	}
	return ""
}

type Recommendation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecommendationId string                 `protobuf:"bytes,1,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority         string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	ImpactScore      float32                `protobuf:"fixed32,5,opt,name=impact_score,json=impactScore,proto3" json:"impact_score,omitempty"`
	ActionItems      []string               `protobuf:"bytes,6,rep,name=action_items,json=actionItems,proto3" json:"action_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_ai_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{13}
}

func (x *Recommendation) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *Recommendation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Recommendation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recommendation) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Recommendation) GetImpactScore() float32 {
	if x != nil {
		return x.ImpactScore
	}
	return 0
}

func (x *Recommendation) GetActionItems() []string {
	if x != nil {
		return x.ActionItems
	}
	return nil
}

type ToolUsage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ToolName             string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Input                string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output               string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	ExecutionTimeSeconds float32                `protobuf:"fixed32,4,opt,name=execution_time_seconds,json=executionTimeSeconds,proto3" json:"execution_time_seconds,omitempty"`
	Success              bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ToolUsage) Reset() {
	*x = ToolUsage{}
	mi := &file_ai_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUsage) ProtoMessage() {}

func (x *ToolUsage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUsage.ProtoReflect.Descriptor instead.
func (*ToolUsage) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{14}
}

func (x *ToolUsage) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolUsage) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ToolUsage) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolUsage) GetExecutionTimeSeconds() float32 {
	if x != nil {
		return x.ExecutionTimeSeconds
	}
	return 0
}

func (x *ToolUsage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WorkflowMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId       string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	StepsExecuted    int32                  `protobuf:"varint,2,opt,name=steps_executed,json=stepsExecuted,proto3" json:"steps_executed,omitempty"`
	TotalTimeSeconds float32                `protobuf:"fixed32,3,opt,name=total_time_seconds,json=totalTimeSeconds,proto3" json:"total_time_seconds,omitempty"`
	Timestamp        string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkflowMetadata) Reset() {
	*x = WorkflowMetadata{}
	mi := &file_ai_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowMetadata) ProtoMessage() {}

func (x *WorkflowMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowMetadata.ProtoReflect.Descriptor instead.
func (*WorkflowMetadata) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{15}
}

func (x *WorkflowMetadata) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowMetadata) GetStepsExecuted() int32 {
	if x != nil {
		return x.StepsExecuted
	}
	return 0
}

func (x *WorkflowMetadata) GetTotalTimeSeconds() float32 {
	if x != nil {
		return x.TotalTimeSeconds
	}
	return 0
}

func (x *WorkflowMetadata) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Insight struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InsightId       string                 `protobuf:"bytes,1,opt,name=insight_id,json=insightId,proto3" json:"insight_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category        string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	DataPoints      map[string]string      `protobuf:"bytes,6,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Insight) Reset() {
	*x = Insight{}
	mi := &file_ai_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Insight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insight) ProtoMessage() {}

func (x *Insight) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insight.ProtoReflect.Descriptor instead.
func (*Insight) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{16}
}

func (x *Insight) GetInsightId() string {
	if x != nil {
		return x.InsightId
	}
	return ""
}

func (x *Insight) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Insight) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Insight) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Insight) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *Insight) GetDataPoints() map[string]string {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

// Ad Generation specific messages
type CreativeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // text, image, video
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreativeRequest) Reset() {
	*x = CreativeRequest{}
	mi := &file_ai_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreativeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreativeRequest) ProtoMessage() {}

func (x *CreativeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreativeRequest.ProtoReflect.Descriptor instead.
func (*CreativeRequest) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{17}
}

func (x *CreativeRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CreativeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreativeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreativeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,3,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreativeResponse) Reset() {
	*x = CreativeResponse{}
	mi := &file_ai_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreativeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreativeResponse) ProtoMessage() {}

func (x *CreativeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreativeResponse.ProtoReflect.Descriptor instead.
func (*CreativeResponse) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{18}
}

func (x *CreativeResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreativeResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreativeResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *CreativeResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Text creative generation
type TextGenerationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Prompt          string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	BrandGuidelines string                 `protobuf:"bytes,2,opt,name=brand_guidelines,json=brandGuidelines,proto3" json:"brand_guidelines,omitempty"`
	TargetAudience  string                 `protobuf:"bytes,3,opt,name=target_audience,json=targetAudience,proto3" json:"target_audience,omitempty"`
	Style           string                 `protobuf:"bytes,4,opt,name=style,proto3" json:"style,omitempty"`
	MaxLength       int32                  `protobuf:"varint,5,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	IncludeBranding bool                   `protobuf:"varint,6,opt,name=include_branding,json=includeBranding,proto3" json:"include_branding,omitempty"`
	Variations      int32                  `protobuf:"varint,7,opt,name=variations,proto3" json:"variations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TextGenerationRequest) Reset() {
	*x = TextGenerationRequest{}
	mi := &file_ai_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextGenerationRequest) ProtoMessage() {}

func (x *TextGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextGenerationRequest.ProtoReflect.Descriptor instead.
func (*TextGenerationRequest) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{19}
}

func (x *TextGenerationRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TextGenerationRequest) GetBrandGuidelines() string {
	if x != nil {
		return x.BrandGuidelines
	}
	return ""
}

func (x *TextGenerationRequest) GetTargetAudience() string {
	if x != nil {
		return x.TargetAudience
	}
	return ""
}

func (x *TextGenerationRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *TextGenerationRequest) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *TextGenerationRequest) GetIncludeBranding() bool {
	if x != nil {
		return x.IncludeBranding
	}
	return false
}

func (x *TextGenerationRequest) GetVariations() int32 {
	if x != nil {
		return x.Variations
	}
	return 0
}

type TextGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeneratedText string                 `protobuf:"bytes,1,opt,name=generated_text,json=generatedText,proto3" json:"generated_text,omitempty"`
	Headline      string                 `protobuf:"bytes,2,opt,name=headline,proto3" json:"headline,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,3,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	Variations    []string               `protobuf:"bytes,4,rep,name=variations,proto3" json:"variations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextGenerationResponse) Reset() {
	*x = TextGenerationResponse{}
	mi := &file_ai_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextGenerationResponse) ProtoMessage() {}

func (x *TextGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextGenerationResponse.ProtoReflect.Descriptor instead.
func (*TextGenerationResponse) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{20}
}

func (x *TextGenerationResponse) GetGeneratedText() string {
	if x != nil {
		return x.GeneratedText
	}
	return ""
}

func (x *TextGenerationResponse) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *TextGenerationResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *TextGenerationResponse) GetVariations() []string {
	if x != nil {
		return x.Variations
	}
	return nil
}

// Image creative generation
type ImageGenerationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Prompt          string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Style           string                 `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	AspectRatio     string                 `protobuf:"bytes,3,opt,name=aspect_ratio,json=aspectRatio,proto3" json:"aspect_ratio,omitempty"`
	BrandAssets     []string               `protobuf:"bytes,4,rep,name=brand_assets,json=brandAssets,proto3" json:"brand_assets,omitempty"`
	IncludeBranding bool                   `protobuf:"varint,5,opt,name=include_branding,json=includeBranding,proto3" json:"include_branding,omitempty"`
	Quality         string                 `protobuf:"bytes,6,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImageGenerationRequest) Reset() {
	*x = ImageGenerationRequest{}
	mi := &file_ai_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageGenerationRequest) ProtoMessage() {}

func (x *ImageGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageGenerationRequest.ProtoReflect.Descriptor instead.
func (*ImageGenerationRequest) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{21}
}

func (x *ImageGenerationRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ImageGenerationRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *ImageGenerationRequest) GetAspectRatio() string {
	if x != nil {
		return x.AspectRatio
	}
	return ""
}

func (x *ImageGenerationRequest) GetBrandAssets() []string {
	if x != nil {
		return x.BrandAssets
	}
	return nil
}

func (x *ImageGenerationRequest) GetIncludeBranding() bool {
	if x != nil {
		return x.IncludeBranding
	}
	return false
}

func (x *ImageGenerationRequest) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

type ImageGenerationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl       string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	AspectRatio    string                 `protobuf:"bytes,2,opt,name=aspect_ratio,json=aspectRatio,proto3" json:"aspect_ratio,omitempty"`
	EnhancedPrompt string                 `protobuf:"bytes,3,opt,name=enhanced_prompt,json=enhancedPrompt,proto3" json:"enhanced_prompt,omitempty"`
	ModelUsed      string                 `protobuf:"bytes,4,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImageGenerationResponse) Reset() {
	*x = ImageGenerationResponse{}
	mi := &file_ai_engine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageGenerationResponse) ProtoMessage() {}

func (x *ImageGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageGenerationResponse.ProtoReflect.Descriptor instead.
func (*ImageGenerationResponse) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{22}
}

func (x *ImageGenerationResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ImageGenerationResponse) GetAspectRatio() string {
	if x != nil {
		return x.AspectRatio
	}
	return ""
}

func (x *ImageGenerationResponse) GetEnhancedPrompt() string {
	if x != nil {
		return x.EnhancedPrompt
	}
	return ""
}

func (x *ImageGenerationResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *ImageGenerationResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Video creative generation
type VideoGenerationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Prompt          string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Style           string                 `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	AspectRatio     string                 `protobuf:"bytes,4,opt,name=aspect_ratio,json=aspectRatio,proto3" json:"aspect_ratio,omitempty"`
	Quality         string                 `protobuf:"bytes,5,opt,name=quality,proto3" json:"quality,omitempty"`
	IncludeBranding bool                   `protobuf:"varint,6,opt,name=include_branding,json=includeBranding,proto3" json:"include_branding,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VideoGenerationRequest) Reset() {
	*x = VideoGenerationRequest{}
	mi := &file_ai_engine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoGenerationRequest) ProtoMessage() {}

func (x *VideoGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoGenerationRequest.ProtoReflect.Descriptor instead.
func (*VideoGenerationRequest) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{23}
}

func (x *VideoGenerationRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *VideoGenerationRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *VideoGenerationRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *VideoGenerationRequest) GetAspectRatio() string {
	if x != nil {
		return x.AspectRatio
	}
	return ""
}

func (x *VideoGenerationRequest) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *VideoGenerationRequest) GetIncludeBranding() bool {
	if x != nil {
		return x.IncludeBranding
	}
	return false
}

type VideoGenerationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VideoUrl        string                 `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	EnhancedPrompt  string                 `protobuf:"bytes,3,opt,name=enhanced_prompt,json=enhancedPrompt,proto3" json:"enhanced_prompt,omitempty"`
	ModelUsed       string                 `protobuf:"bytes,4,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VideoGenerationResponse) Reset() {
	*x = VideoGenerationResponse{}
	mi := &file_ai_engine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoGenerationResponse) ProtoMessage() {}

func (x *VideoGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoGenerationResponse.ProtoReflect.Descriptor instead.
func (*VideoGenerationResponse) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{24}
}

func (x *VideoGenerationResponse) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *VideoGenerationResponse) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *VideoGenerationResponse) GetEnhancedPrompt() string {
	if x != nil {
		return x.EnhancedPrompt
	}
	return ""
}

func (x *VideoGenerationResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *VideoGenerationResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Analysis messages
type AnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	AnalysisType  string                 `protobuf:"bytes,2,opt,name=analysis_type,json=analysisType,proto3" json:"analysis_type,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	mi := &file_ai_engine_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{25}
}

func (x *AnalysisRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *AnalysisRequest) GetAnalysisType() string {
	if x != nil {
		return x.AnalysisType
	}
	return ""
}

func (x *AnalysisRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type AnalysisResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AnalysisResult  string                 `protobuf:"bytes,1,opt,name=analysis_result,json=analysisResult,proto3" json:"analysis_result,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Metrics         map[string]string      `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Insights        []string               `protobuf:"bytes,4,rep,name=insights,proto3" json:"insights,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_ai_engine_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{26}
}

func (x *AnalysisResponse) GetAnalysisResult() string {
	if x != nil {
		return x.AnalysisResult
	}
	return ""
}

func (x *AnalysisResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *AnalysisResponse) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *AnalysisResponse) GetInsights() []string {
	if x != nil {
		return x.Insights
	}
	return nil
}

// Agent messages
type AgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Tools         []string               `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_ai_engine_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{27}
}

func (x *AgentRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AgentRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *AgentRequest) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

type AgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	ActionsTaken  []string               `protobuf:"bytes,2,rep,name=actions_taken,json=actionsTaken,proto3" json:"actions_taken,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_ai_engine_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_engine_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_ai_engine_proto_rawDescGZIP(), []int{28}
}

func (x *AgentResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *AgentResponse) GetActionsTaken() []string {
	if x != nil {
		return x.ActionsTaken
	}
	return nil
}

func (x *AgentResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_ai_engine_proto protoreflect.FileDescriptor

const file_ai_engine_proto_rawDesc = "" +
	"\n" +
	"\x0fai_engine.proto\x12\tai_engine\"\x9b\x03\n" +
	"\x17GenerateCreativeRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12#\n" +
	"\rcreative_type\x18\x02 \x01(\tR\fcreativeType\x12R\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v22.ai_engine.GenerateCreativeRequest.ParametersEntryR\n" +
	"parameters\x12\x1c\n" +
	"\tplatforms\x18\x04 \x03(\tR\tplatforms\x12B\n" +
	"\x0ftarget_audience\x18\x05 \x01(\v2\x19.ai_engine.TargetAudienceR\x0etargetAudience\x12E\n" +
	"\x10brand_guidelines\x18\x06 \x01(\v2\x1a.ai_engine.BrandGuidelinesR\x0fbrandGuidelines\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x18GenerateCreativeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\n" +
	"variations\x18\x03 \x03(\v2\x1c.ai_engine.CreativeVariationR\n" +
	"variations\x129\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1d.ai_engine.GenerationMetadataR\bmetadata\"\xfe\x01\n" +
	"\x16AnalyzeCampaignRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x18\n" +
	"\ametrics\x18\x02 \x03(\tR\ametrics\x12#\n" +
	"\ranalysis_type\x18\x03 \x01(\tR\fanalysisType\x12H\n" +
	"\afilters\x18\x04 \x03(\v2..ai_engine.AnalyzeCampaignRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x01\n" +
	"\x17AnalyzeCampaignResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\banalysis\x18\x03 \x01(\v2\x19.ai_engine.AnalysisResultR\banalysis\x12C\n" +
	"\x0frecommendations\x18\x04 \x03(\v2\x19.ai_engine.RecommendationR\x0frecommendations\"\xa8\x02\n" +
	"\x14AgentWorkflowRequest\x12#\n" +
	"\rworkflow_type\x18\x01 \x01(\tR\fworkflowType\x12\x1d\n" +
	"\n" +
	"user_query\x18\x02 \x01(\tR\tuserQuery\x12F\n" +
	"\acontext\x18\x03 \x03(\v2,.ai_engine.AgentWorkflowRequest.ContextEntryR\acontext\x12'\n" +
	"\x0favailable_tools\x18\x04 \x03(\tR\x0eavailableTools\x12\x1f\n" +
	"\vcampaign_id\x18\x05 \x01(\tR\n" +
	"campaignId\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\x15AgentWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x123\n" +
	"\n" +
	"tools_used\x18\x04 \x03(\v2\x14.ai_engine.ToolUsageR\ttoolsUsed\x127\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1b.ai_engine.WorkflowMetadataR\bmetadata\"\xff\x01\n" +
	"\x0fInsightsRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\finsight_type\x18\x02 \x01(\tR\vinsightType\x12\x1d\n" +
	"\n" +
	"time_range\x18\x03 \x01(\tR\ttimeRange\x12J\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2*.ai_engine.InsightsRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x10InsightsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\binsights\x18\x03 \x03(\v2\x12.ai_engine.InsightR\binsights\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\"\x81\x03\n" +
	"\x0eTargetAudience\x12O\n" +
	"\fdemographics\x18\x01 \x03(\v2+.ai_engine.TargetAudience.DemographicsEntryR\fdemographics\x12\x1c\n" +
	"\tinterests\x18\x02 \x03(\tR\tinterests\x12\x1c\n" +
	"\tbehaviors\x18\x03 \x03(\tR\tbehaviors\x12\\\n" +
	"\x11custom_attributes\x18\x04 \x03(\v2/.ai_engine.TargetAudience.CustomAttributesEntryR\x10customAttributes\x1a?\n" +
	"\x11DemographicsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15CustomAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x02\n" +
	"\x0fBrandGuidelines\x12\x16\n" +
	"\x06colors\x18\x01 \x03(\tR\x06colors\x12\x14\n" +
	"\x05fonts\x18\x02 \x03(\tR\x05fonts\x12\x1d\n" +
	"\n" +
	"voice_tone\x18\x03 \x01(\tR\tvoiceTone\x12]\n" +
	"\x11style_preferences\x18\x04 \x03(\v20.ai_engine.BrandGuidelines.StylePreferencesEntryR\x10stylePreferences\x12!\n" +
	"\fbrand_assets\x18\x05 \x03(\tR\vbrandAssets\x1aC\n" +
	"\x15StylePreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x03\n" +
	"\x11CreativeVariation\x12!\n" +
	"\fvariation_id\x18\x01 \x01(\tR\vvariationId\x12\x1f\n" +
	"\vcontent_url\x18\x02 \x01(\tR\n" +
	"contentUrl\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12k\n" +
	"\x15generation_parameters\x18\x04 \x03(\v26.ai_engine.CreativeVariation.GenerationParametersEntryR\x14generationParameters\x12+\n" +
	"\x11performance_score\x18\x05 \x01(\x02R\x10performanceScore\x12\x1f\n" +
	"\vis_approved\x18\x06 \x01(\bR\n" +
	"isApproved\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x1aG\n" +
	"\x19GenerationParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x02\n" +
	"\x12GenerationMetadata\x12\x1d\n" +
	"\n" +
	"model_used\x18\x01 \x01(\tR\tmodelUsed\x12M\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2-.ai_engine.GenerationMetadata.ParametersEntryR\n" +
	"parameters\x126\n" +
	"\x17generation_time_seconds\x18\x03 \x01(\x02R\x15generationTimeSeconds\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x02\n" +
	"\x0eAnalysisResult\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12@\n" +
	"\ametrics\x18\x02 \x03(\v2&.ai_engine.AnalysisResult.MetricsEntryR\ametrics\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1a\n" +
	"\binsights\x18\x04 \x03(\tR\binsights\x12)\n" +
	"\x10confidence_score\x18\x05 \x01(\tR\x0fconfidenceScore\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xd7\x01\n" +
	"\x0eRecommendation\x12+\n" +
	"\x11recommendation_id\x18\x01 \x01(\tR\x10recommendationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12!\n" +
	"\fimpact_score\x18\x05 \x01(\x02R\vimpactScore\x12!\n" +
	"\faction_items\x18\x06 \x03(\tR\vactionItems\"\xa6\x01\n" +
	"\tToolUsage\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x124\n" +
	"\x16execution_time_seconds\x18\x04 \x01(\x02R\x14executionTimeSeconds\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\"\xa6\x01\n" +
	"\x10WorkflowMetadata\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12%\n" +
	"\x0esteps_executed\x18\x02 \x01(\x05R\rstepsExecuted\x12,\n" +
	"\x12total_time_seconds\x18\x03 \x01(\x02R\x10totalTimeSeconds\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\xab\x02\n" +
	"\aInsight\x12\x1d\n" +
	"\n" +
	"insight_id\x18\x01 \x01(\tR\tinsightId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12)\n" +
	"\x10confidence_score\x18\x05 \x01(\x02R\x0fconfidenceScore\x12C\n" +
	"\vdata_points\x18\x06 \x03(\v2\".ai_engine.Insight.DataPointsEntryR\n" +
	"dataPoints\x1a=\n" +
	"\x0fDataPointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x01\n" +
	"\x0fCreativeRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.ai_engine.CreativeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x01\n" +
	"\x10CreativeResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"model_used\x18\x03 \x01(\tR\tmodelUsed\x12E\n" +
	"\bmetadata\x18\x04 \x03(\v2).ai_engine.CreativeResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\x15TextGenerationRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12)\n" +
	"\x10brand_guidelines\x18\x02 \x01(\tR\x0fbrandGuidelines\x12'\n" +
	"\x0ftarget_audience\x18\x03 \x01(\tR\x0etargetAudience\x12\x14\n" +
	"\x05style\x18\x04 \x01(\tR\x05style\x12\x1d\n" +
	"\n" +
	"max_length\x18\x05 \x01(\x05R\tmaxLength\x12)\n" +
	"\x10include_branding\x18\x06 \x01(\bR\x0fincludeBranding\x12\x1e\n" +
	"\n" +
	"variations\x18\a \x01(\x05R\n" +
	"variations\"\x9a\x01\n" +
	"\x16TextGenerationResponse\x12%\n" +
	"\x0egenerated_text\x18\x01 \x01(\tR\rgeneratedText\x12\x1a\n" +
	"\bheadline\x18\x02 \x01(\tR\bheadline\x12\x1d\n" +
	"\n" +
	"model_used\x18\x03 \x01(\tR\tmodelUsed\x12\x1e\n" +
	"\n" +
	"variations\x18\x04 \x03(\tR\n" +
	"variations\"\xd1\x01\n" +
	"\x16ImageGenerationRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05style\x18\x02 \x01(\tR\x05style\x12!\n" +
	"\faspect_ratio\x18\x03 \x01(\tR\vaspectRatio\x12!\n" +
	"\fbrand_assets\x18\x04 \x03(\tR\vbrandAssets\x12)\n" +
	"\x10include_branding\x18\x05 \x01(\bR\x0fincludeBranding\x12\x18\n" +
	"\aquality\x18\x06 \x01(\tR\aquality\"\xac\x02\n" +
	"\x17ImageGenerationResponse\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12!\n" +
	"\faspect_ratio\x18\x02 \x01(\tR\vaspectRatio\x12'\n" +
	"\x0fenhanced_prompt\x18\x03 \x01(\tR\x0eenhancedPrompt\x12\x1d\n" +
	"\n" +
	"model_used\x18\x04 \x01(\tR\tmodelUsed\x12L\n" +
	"\bmetadata\x18\x05 \x03(\v20.ai_engine.ImageGenerationResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\x16VideoGenerationRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05style\x18\x02 \x01(\tR\x05style\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05R\x0fdurationSeconds\x12!\n" +
	"\faspect_ratio\x18\x04 \x01(\tR\vaspectRatio\x12\x18\n" +
	"\aquality\x18\x05 \x01(\tR\aquality\x12)\n" +
	"\x10include_branding\x18\x06 \x01(\bR\x0fincludeBranding\"\xb4\x02\n" +
	"\x17VideoGenerationResponse\x12\x1b\n" +
	"\tvideo_url\x18\x01 \x01(\tR\bvideoUrl\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x05R\x0fdurationSeconds\x12'\n" +
	"\x0fenhanced_prompt\x18\x03 \x01(\tR\x0eenhancedPrompt\x12\x1d\n" +
	"\n" +
	"model_used\x18\x04 \x01(\tR\tmodelUsed\x12L\n" +
	"\bmetadata\x18\x05 \x03(\v20.ai_engine.VideoGenerationResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x01\n" +
	"\x0fAnalysisRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12#\n" +
	"\ranalysis_type\x18\x02 \x01(\tR\fanalysisType\x12J\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2*.ai_engine.AnalysisRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x02\n" +
	"\x10AnalysisResponse\x12'\n" +
	"\x0fanalysis_result\x18\x01 \x01(\tR\x0eanalysisResult\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x02R\x0fconfidenceScore\x12B\n" +
	"\ametrics\x18\x03 \x03(\v2(.ai_engine.AnalysisResponse.MetricsEntryR\ametrics\x12\x1a\n" +
	"\binsights\x18\x04 \x03(\tR\binsights\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\fAgentRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x14\n" +
	"\x05tools\x18\x03 \x03(\tR\x05tools\"h\n" +
	"\rAgentResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12#\n" +
	"\ractions_taken\x18\x02 \x03(\tR\factionsTaken\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result2\xcb\x04\n" +
	"\bAIEngine\x12K\n" +
	"\x10GenerateCreative\x12\x1a.ai_engine.CreativeRequest\x1a\x1b.ai_engine.CreativeResponse\x12[\n" +
	"\x14GenerateTextCreative\x12 .ai_engine.TextGenerationRequest\x1a!.ai_engine.TextGenerationResponse\x12^\n" +
	"\x15GenerateImageCreative\x12!.ai_engine.ImageGenerationRequest\x1a\".ai_engine.ImageGenerationResponse\x12^\n" +
	"\x15GenerateVideoCreative\x12!.ai_engine.VideoGenerationRequest\x1a\".ai_engine.VideoGenerationResponse\x12I\n" +
	"\x0eAnalyzeContent\x12\x1a.ai_engine.AnalysisRequest\x1a\x1b.ai_engine.AnalysisResponse\x12K\n" +
	"\x10GenerateInsights\x12\x1a.ai_engine.InsightsRequest\x1a\x1b.ai_engine.InsightsResponse\x12=\n" +
	"\bRunAgent\x12\x17.ai_engine.AgentRequest\x1a\x18.ai_engine.AgentResponseB<Z:github.com/startupmanch/ceaser-ad-business/proto/ai_engineb\x06proto3"

var (
	file_ai_engine_proto_rawDescOnce sync.Once
	file_ai_engine_proto_rawDescData []byte
)

func file_ai_engine_proto_rawDescGZIP() []byte {
	file_ai_engine_proto_rawDescOnce.Do(func() {
		file_ai_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_engine_proto_rawDesc), len(file_ai_engine_proto_rawDesc)))
	})
	return file_ai_engine_proto_rawDescData
}

var file_ai_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_ai_engine_proto_goTypes = []any{
	(*GenerateCreativeRequest)(nil),  // 0: ai_engine.GenerateCreativeRequest
	(*GenerateCreativeResponse)(nil), // 1: ai_engine.GenerateCreativeResponse
	(*AnalyzeCampaignRequest)(nil),   // 2: ai_engine.AnalyzeCampaignRequest
	(*AnalyzeCampaignResponse)(nil),  // 3: ai_engine.AnalyzeCampaignResponse
	(*AgentWorkflowRequest)(nil),     // 4: ai_engine.AgentWorkflowRequest
	(*AgentWorkflowResponse)(nil),    // 5: ai_engine.AgentWorkflowResponse
	(*InsightsRequest)(nil),          // 6: ai_engine.InsightsRequest
	(*InsightsResponse)(nil),         // 7: ai_engine.InsightsResponse
	(*TargetAudience)(nil),           // 8: ai_engine.TargetAudience
	(*BrandGuidelines)(nil),          // 9: ai_engine.BrandGuidelines
	(*CreativeVariation)(nil),        // 10: ai_engine.CreativeVariation
	(*GenerationMetadata)(nil),       // 11: ai_engine.GenerationMetadata
	(*AnalysisResult)(nil),           // 12: ai_engine.AnalysisResult
	(*Recommendation)(nil),           // 13: ai_engine.Recommendation
	(*ToolUsage)(nil),                // 14: ai_engine.ToolUsage
	(*WorkflowMetadata)(nil),         // 15: ai_engine.WorkflowMetadata
	(*Insight)(nil),                  // 16: ai_engine.Insight
	(*CreativeRequest)(nil),          // 17: ai_engine.CreativeRequest
	(*CreativeResponse)(nil),         // 18: ai_engine.CreativeResponse
	(*TextGenerationRequest)(nil),    // 19: ai_engine.TextGenerationRequest
	(*TextGenerationResponse)(nil),   // 20: ai_engine.TextGenerationResponse
	(*ImageGenerationRequest)(nil),   // 21: ai_engine.ImageGenerationRequest
	(*ImageGenerationResponse)(nil),  // 22: ai_engine.ImageGenerationResponse
	(*VideoGenerationRequest)(nil),   // 23: ai_engine.VideoGenerationRequest
	(*VideoGenerationResponse)(nil),  // 24: ai_engine.VideoGenerationResponse
	(*AnalysisRequest)(nil),          // 25: ai_engine.AnalysisRequest
	(*AnalysisResponse)(nil),         // 26: ai_engine.AnalysisResponse
	(*AgentRequest)(nil),             // 27: ai_engine.AgentRequest
	(*AgentResponse)(nil),            // 28: ai_engine.AgentResponse
	nil,                              // 29: ai_engine.GenerateCreativeRequest.ParametersEntry
	nil,                              // 30: ai_engine.AnalyzeCampaignRequest.FiltersEntry
	nil,                              // 31: ai_engine.AgentWorkflowRequest.ContextEntry
	nil,                              // 32: ai_engine.InsightsRequest.ParametersEntry
	nil,                              // 33: ai_engine.TargetAudience.DemographicsEntry
	nil,                              // 34: ai_engine.TargetAudience.CustomAttributesEntry
	nil,                              // 35: ai_engine.BrandGuidelines.StylePreferencesEntry
	nil,                              // 36: ai_engine.CreativeVariation.GenerationParametersEntry
	nil,                              // 37: ai_engine.GenerationMetadata.ParametersEntry
	nil,                              // 38: ai_engine.AnalysisResult.MetricsEntry
	nil,                              // 39: ai_engine.Insight.DataPointsEntry
	nil,                              // 40: ai_engine.CreativeRequest.MetadataEntry
	nil,                              // 41: ai_engine.CreativeResponse.MetadataEntry
	nil,                              // 42: ai_engine.ImageGenerationResponse.MetadataEntry
	nil,                              // 43: ai_engine.VideoGenerationResponse.MetadataEntry
	nil,                              // 44: ai_engine.AnalysisRequest.ParametersEntry
	nil,                              // 45: ai_engine.AnalysisResponse.MetricsEntry
}
var file_ai_engine_proto_depIdxs = []int32{
	29, // 0: ai_engine.GenerateCreativeRequest.parameters:type_name -> ai_engine.GenerateCreativeRequest.ParametersEntry
	8,  // 1: ai_engine.GenerateCreativeRequest.target_audience:type_name -> ai_engine.TargetAudience
	9,  // 2: ai_engine.GenerateCreativeRequest.brand_guidelines:type_name -> ai_engine.BrandGuidelines
	10, // 3: ai_engine.GenerateCreativeResponse.variations:type_name -> ai_engine.CreativeVariation
	11, // 4: ai_engine.GenerateCreativeResponse.metadata:type_name -> ai_engine.GenerationMetadata
	30, // 5: ai_engine.AnalyzeCampaignRequest.filters:type_name -> ai_engine.AnalyzeCampaignRequest.FiltersEntry
	12, // 6: ai_engine.AnalyzeCampaignResponse.analysis:type_name -> ai_engine.AnalysisResult
	13, // 7: ai_engine.AnalyzeCampaignResponse.recommendations:type_name -> ai_engine.Recommendation
	31, // 8: ai_engine.AgentWorkflowRequest.context:type_name -> ai_engine.AgentWorkflowRequest.ContextEntry
	14, // 9: ai_engine.AgentWorkflowResponse.tools_used:type_name -> ai_engine.ToolUsage
	15, // 10: ai_engine.AgentWorkflowResponse.metadata:type_name -> ai_engine.WorkflowMetadata
	32, // 11: ai_engine.InsightsRequest.parameters:type_name -> ai_engine.InsightsRequest.ParametersEntry
	16, // 12: ai_engine.InsightsResponse.insights:type_name -> ai_engine.Insight
	33, // 13: ai_engine.TargetAudience.demographics:type_name -> ai_engine.TargetAudience.DemographicsEntry
	34, // 14: ai_engine.TargetAudience.custom_attributes:type_name -> ai_engine.TargetAudience.CustomAttributesEntry
	35, // 15: ai_engine.BrandGuidelines.style_preferences:type_name -> ai_engine.BrandGuidelines.StylePreferencesEntry
	36, // 16: ai_engine.CreativeVariation.generation_parameters:type_name -> ai_engine.CreativeVariation.GenerationParametersEntry
	37, // 17: ai_engine.GenerationMetadata.parameters:type_name -> ai_engine.GenerationMetadata.ParametersEntry
	38, // 18: ai_engine.AnalysisResult.metrics:type_name -> ai_engine.AnalysisResult.MetricsEntry
	39, // 19: ai_engine.Insight.data_points:type_name -> ai_engine.Insight.DataPointsEntry
	40, // 20: ai_engine.CreativeRequest.metadata:type_name -> ai_engine.CreativeRequest.MetadataEntry
	41, // 21: ai_engine.CreativeResponse.metadata:type_name -> ai_engine.CreativeResponse.MetadataEntry
	42, // 22: ai_engine.ImageGenerationResponse.metadata:type_name -> ai_engine.ImageGenerationResponse.MetadataEntry
	43, // 23: ai_engine.VideoGenerationResponse.metadata:type_name -> ai_engine.VideoGenerationResponse.MetadataEntry
	44, // 24: ai_engine.AnalysisRequest.parameters:type_name -> ai_engine.AnalysisRequest.ParametersEntry
	45, // 25: ai_engine.AnalysisResponse.metrics:type_name -> ai_engine.AnalysisResponse.MetricsEntry
	17, // 26: ai_engine.AIEngine.GenerateCreative:input_type -> ai_engine.CreativeRequest
	19, // 27: ai_engine.AIEngine.GenerateTextCreative:input_type -> ai_engine.TextGenerationRequest
	21, // 28: ai_engine.AIEngine.GenerateImageCreative:input_type -> ai_engine.ImageGenerationRequest
	23, // 29: ai_engine.AIEngine.GenerateVideoCreative:input_type -> ai_engine.VideoGenerationRequest
	25, // 30: ai_engine.AIEngine.AnalyzeContent:input_type -> ai_engine.AnalysisRequest
	6,  // 31: ai_engine.AIEngine.GenerateInsights:input_type -> ai_engine.InsightsRequest
	27, // 32: ai_engine.AIEngine.RunAgent:input_type -> ai_engine.AgentRequest
	18, // 33: ai_engine.AIEngine.GenerateCreative:output_type -> ai_engine.CreativeResponse
	20, // 34: ai_engine.AIEngine.GenerateTextCreative:output_type -> ai_engine.TextGenerationResponse
	22, // 35: ai_engine.AIEngine.GenerateImageCreative:output_type -> ai_engine.ImageGenerationResponse
	24, // 36: ai_engine.AIEngine.GenerateVideoCreative:output_type -> ai_engine.VideoGenerationResponse
	26, // 37: ai_engine.AIEngine.AnalyzeContent:output_type -> ai_engine.AnalysisResponse
	7,  // 38: ai_engine.AIEngine.GenerateInsights:output_type -> ai_engine.InsightsResponse
	28, // 39: ai_engine.AIEngine.RunAgent:output_type -> ai_engine.AgentResponse
	33, // [33:40] is the sub-list for method output_type
	26, // [26:33] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_ai_engine_proto_init() }
func file_ai_engine_proto_init() {
	if File_ai_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_engine_proto_rawDesc), len(file_ai_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_engine_proto_goTypes,
		DependencyIndexes: file_ai_engine_proto_depIdxs,
		MessageInfos:      file_ai_engine_proto_msgTypes,
	}.Build()
	File_ai_engine_proto = out.File
	file_ai_engine_proto_goTypes = nil
	file_ai_engine_proto_depIdxs = nil
}
