{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ceaser-ad-business.fullname" . }}-network-policy
  labels:
    {{- include "ceaser-ad-business.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ceaser-ad-business.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
    # Allow internal communication between services
    - from:
        - podSelector:
            matchLabels:
              {{- include "ceaser-ad-business.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 50051
        - protocol: TCP
          port: 6333
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 5432
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
    # Allow internal communication
    - to:
        - podSelector:
            matchLabels:
              {{- include "ceaser-ad-business.selectorLabels" . | nindent 14 }}
    # Allow external API calls (OpenAI, Google, etc.)
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
